### ISSUE TITLE
유튜브 임베드를 할 경우 썸네일이 생성이 안되는데 원래 지원이 됐었나요?

### ISSUE THREAD

**Issue by jominhyun** [cydemo/rx-module-preview#10]
유튜브 임베드를 할 경우 
첨부파일에 썸네일이 생성이 안되고 있어서요.
제 기억에는 원래 지원이 됐던걸로 기억하는데
어드민 프리뷰 설정에 들어가면 썸네일 설정 부분이 또 없는걸로봐서는 아닌것 같기도하고....
궁금하네요

**Comment by jominhyun** [comment]
썸네일은 만들어지네요; 다만 첨부파일에 보이질 않으니
제 서버문제인가봅니다

**Comment by cydemo** [comment]
서버문제는 아니고 원래 외부이미지로만 로드합니다.
현재는 인스타그램이나 페이스북처럼 썸네일 url이 가변적인 몇몇 미디어 콘텐츠에서만 썸네일을 첨부 파일로 변환을 해주고 있고요.
유튜브처럼 반영구적인 썸네일 url은 그냥 외부이미지로만 가져오고 있습니다.
