### ISSUE TITLE
문서뷰어가 작동하지 않음

### ISSUE THREAD

**Issue by jominhyun** [cydemo/rx-module-preview#3]
문서뷰어 애드온이 통합되어있다고해서 pdf, 엑셀파일등을 파일업로드하고 등록을 해도 뷰어기능이 작동하지 않아요 저만그런가요 ㅎㅎ;;

**Comment by cydemo** [comment]
모듈 설정에서 pdf와 ms office 체크하신 거죠?
파일 본문 삽입 시에 에러 메시지 나오는 게 있으면 알려주세요.

**Comment by mAKEkr** [comment]
@cydemo 제가 시도했을때는 첨부해도 관련 메세지 자체가 표시가 안되는걸 보면 FileUploader쪽이 연동이 안되고있는것으로 생각합니다.

**Comment by jominhyun** [comment]
> 모듈 설정에서 pdf와 ms office 체크하신 거죠? 파일 본문 삽입 시에 에러 메시지 나오는 게 있으면 알려주세요.

네 모두 체크했습니다. ㅎㅎ;; 링크프리뷰 게시글 하단 댓글이 하루만에 수십개의 대댓글이달려있네요.
다른분들도 비슷한 문제를 겪고있나봅니다.

**Comment by cydemo** [comment]
> 네 모두 체크했습니다. ㅎㅎ;; 링크프리뷰 게시글 하단 댓글이 하루만에 수십개의 대댓글이달려있네요. 다른분들도 비슷한 문제를 겪고있나봅니다.

피드백이 댓글 120개를 주고 받은 다음에야 끝나가네요. 0.2.0 버전에 패치가 있으니 한번 적용해보시는 것도 좋을 듯합니다.
https://xetown.com/files/download/link/1850763/fb98ac08d17d2aea9c9256caf4075772/preview.patch.20241223.zip

**Comment by cydemo** [comment]
@jominhyun 0.2.1 버전으로 업데이트하면서 해당 문제의 개선이 이뤄진 것 같습니다. 확인해보시기 바랍니다.
