### ISSUE TITLE
youtube 임베드시 maxresdefault를 기본으로 설정하거나 가운데 정렬하도록 변경

### ISSUE THREAD

**Issue by mAKEkr** [cydemo/rx-module-preview#8]
현재 대부분 영상들이 16:9 비율에 맞춰 나오고 있는 반면 youtube의 oembed에서 표시해주는 기본 섬네일의 비율은 4:3입니다.

그래서 iframe 로딩 이전에 4:3의 블랙바를 잠깐이라도 보게되는데, 관련해서 수정되었으면 좋겠습니다.

**Comment by cydemo** [comment]
저도 블랙바 때문에 거슬리긴 하더군요.

예전에도 maxresdefault로 가려 했었는데...
옛날 영상들 (또는 최대화질 자체가 480 이하인 영상들) 가운데는 maxresdefault가 없는 경우가 있더라구요.
그래서 mqdefault로 가볼까 했는데 이건 해상도가 너무 떨어지고...
결과적으로는 그냥 귀찮기도 하고 해서 oembed에서 쏴주는 대로 hqdefault로 갔던 기억이 있습니다.

대안은 두 가지 정도로 생각됩니다.

1. maxresdefault 이미지 엑박 확인하고 엑박이면 mqdefault로 바꿔주는 것도 방법일 것 같은데, 어쩌면 괜히 동작 시간이 길어질 것 같고요.

2, 아니면 hqdefault 이미지를 가로세로 가운데 정렬로 하는 건 어떨까요? 아, 이건 게시판 목록에서 썸네일에서 블랙바가 그대로 노출되는 경우도 생기겠네요.

**Comment by mAKEkr** [comment]
관련하여 소스코드를 아침까지 들여다봤었는데, oembed에 리퀘스트를 날려 데이터를 확인하는 과정중에 비율을 만드신게 있더라구요.

16:9 혹은 2:1의 비율을 벗어나면 hqdefault, 아니라면 maxresdefault(혹은 hq720) 하면 문제가 없지않을까 싶은데 어떤 영상들에 보일지 안보일지 모르다보니 조심스럽네요. 조금 이전 영상들까지 찾아보면서 체크하는게 좋을것같아요

**Comment by cydemo** [comment]
네, 인코딩하는 영상들의 비율이 제각각이다보니 iframe의 세로 사이즈를 제대로 잡으려면 그렇게 해줘야 하겠더라구요.
근데 또 어떤 경우는 oembed로 확인되는 비율은 4:3인데 실제 영상은 16:9로 나오는 경우도 있어서 유튜브 쪽의 콘텐츠 관리 방식이 생각보다 매끄럽지는 않은 것 같다는 생각도 듭니다.

유튜브에서 뿌려주는 썸네일은 16:9를 기본으로 하는 것 같습니다.
그래서 4:3비율의 영상이라 하더라도, 16:9 사이즈로 썸네일을 기본 생성하기 때문에 썸네일에 양옆 레터박스는 기본으로 생기더라구요. https://i.ytimg.com/vi/2Ut86Xv_AX0/maxresdefault.jpg
이때 4:3 비율의 hqdefault 썸네일을 출력하면 (양옆 레터박스가 사라지는 게 아니라!) 양옆 레터박스가 있는 16:9 이미지 위아래로 레터박스를 추가해주는 방식입니다ㅜㅜ https://i.ytimg.com/vi/2Ut86Xv_AX0/hqdefault.jpg

그래서 썸네일은 그냥 maxresdefault로 가는 쪽이 속편하지 싶습니다.
옛날 영상이어서 썸네일이 없으면 onerror 정도로 체크해서 엑박이면 mqdefault로 바꿔주고요.

**Comment by cydemo** [comment]
0.2.2로 업데이트하면서 해당 이슈 반영했습니다. 감사합니다!
